const fs = require('fs')
const chalk = require('chalk')
global.menulist = [ 
                  "groupmenu",
                  "ownermenu",
                  "antilinkmenu",
                  "stalkermenu",
                  "downloadmenu",
                  "convertmenu",
                  "searchmenu",
                  "weebmenu",
                  "stickermenu",
                  "wallpapermenu",
                  "logomakermenu",
                  "textpromenu",
                  "randomimagemenu",
                  "animereactionmenu",
                  "audiomenu",
                  "gamemenu",
                  "coremenu",
                  "funmenu",
                  "toolmenu",
                  "anonymousmenu",
                  "nsfwmenu"
]
global.groupmenu = [
                  "banchat",
                  "resetgclink",
                  "mysoulmate",
                  "couple",
                  "leavegc",
                  "remove-me",
                  "setdescription *-text-*",
                  "setgcpp *-pic-*",
                  "setgcname *-text-*",
                  "add *-user-*",
                  "remove *-user-*",
                  "promote *-user-*",
                  "demote *-user-*",
                  "admins *-text-*",
                  "tagall",
                  "hidetag",
                  "editinfo",
                  "autosticker",
                  "autostickerpc",
                  "autoreply",
                  "mute",
                  "linkgc",
                  "ephemeral",
                  "groupsettings",
                  "delete",
                  "deletethis",
                  "listpc",
                  "listgc",
                  "listonline",
                  "tagme",
                  "couplepp",
                  "group-safety",
                  "description",
                  "profile",
                  "antitoxic",
                  "antivirus",
                  "bc-this-group",
                  "bctext",
                  "bcvideo",
                  "bcimage"
]
global.ownermenu = [
                  "ban",
                  "unban",
                  "banchat",
                  "co-owner",
                  "deletethis",
                  "autostickerpc",
                  "autoreply",
        //          "listpc",
       //           "listgc",
                  "modes",
                  "prefix",
                  "single-prefix",
                  "multi-prefix",
                  "all-prefix",
                  "no-prefix",
                  "settings",
                  "self",
                  "public",
                  "setstatus",
     //             "update",
            /*      "bc-this-group",
                  "english-lan",
                  "french-lan",
                  "arabic-lan",*/
                  "language",
                  "welcome",
                  "goodbye",
                  "promote-msg",
                  "demote-msg",
                  "anticall",
                  "autoblock"
         //         "active",
          //        "deactive"
]
global.antilinkmenu = [
                  "antilink",
                  "antilinkall",
                  "antilinkgc",
                  "antilinkfb",
                  "antilinktwt",
                  "antiwame",
                  "antilinktg",
                  "antilinktt",
                  "antilinkig",
                  "antilinkytch",
                  "antilinkytvd"
]
global.stalkermenu = [
                  "ig",
                  "github",
                  "github-repo",
                  "ip"
]
global.downloadmenu = [
                  "soundcloud *-link-*",
                  "zippyshare",
                  "apk *-text-*",
                  "gitclone *-link-*",
                  "playstore *-text-*",
                  "happymod",
                  "xnxx2 *-link-*",
                  "xvideos2 *-link-*"
]
global.convertmenu = [
                  "toimg",
                  "tomp4",
                  "tomp3",
                  "toVN",
                  "togif",
                  "tourl",
              //    "readmore",
                  "toviewonce",
                  "tinyurl"
               //   Android Download 👉: https://fontboard.page.link/share

              //    iOS Download 👉: https://apps.apple.com/
]
global.searchmenu = [
                  "yts *-text-*",
                  "gimage",
                  "google",
                  "mp4 *-link-*",
                  "lyrics",
                  "manga",
                  "anime",
      //            "film",
           //   /"searchgc",
                  "song",
                  "play",
                  "ytmp3 *-text-*",
                  "ytmp32 *-link-*",
                  "ytmp4 *-text-*",
                  "ytmp42 *-link-*",
                  "ytshorts *-text-*",
                  "image *-text-*",
                  "pinterest *-text-*",
                  "ringtone *-text-*",
                  "xnxx *-text-*",
                  "xvideos *-text-*",
              //    "xnxx2 *-link-*",
             //     "xvideos2 *-link-*",
       //           "ssweb *-text-*",
          //        "ssweb2 *-text-*"
]
global.weebmenu = [
                  "awoo",
          //        "ahegao",
                  "akira",
                  "akiyama",
                  "ana",
                  "asuna",
                  "ayuzawa",
                  "boruto",
                  "chitanda",
                  "chitoge",
                  "deidara",
                  "doraemon",
                  "elaina",
                  "emilia",
                  "erza",
                  "fox_girl",
                  "gremory",
                  "hestia",
                  "hinata",
                  "husbu",
                  "inori",
                  "isuzu",
                  "itachi",
                  "itori",
                  "kaga",
                  "kagura",
                  "kakashi",
                  "kaori",
                  "kaneki",
                  "kosaki",
                  "kotori",
                  "kuriyama",
                  "kuroha",
                  "kurumi",
                  "loli",
                  "madara",
                  "megumin",
                  "megumin2",
                  "mikasa",
                  "miku",
                  "minato",
                  "naruto",
                  "natsukawa",
                  "nekonime",
                  "neko",
                  "neko2",
                  "nezuko",
                  "nishimiya",
                  "onepiece",
                  "pokemone",
                  "rem",
                  "rize",
                  "sagiri",
                  "sakura",
                  "shina",
                  "shinka",
                  "shizuka",
                  "shota",
                  "tomori",
                  "toukachan",
                  "tsunade",
                  "waifu",
                  "yaoi",
                  "yuki"
]
global.stickermenu = [
                  "cry",
                  "kill",
                  "kick",
                  "hug",
                  "pat",
                  "lick",
                  "kiss",
                  "bite",
                  "yeet",
                  "bully",
                  "bonk",
                  "wink",
                  "poke",
                  "nom",
                  "slap",
                  "smile",
                  "wave",
                  "blush",
                  "glomp",
                  "happy",
                  "cringe",
                  "dance",
                  "cuddle",
                  "highfive",
                  "handhold",
         /*         "amongus",
                  "gojosatoru",
                  "animegif",
                  "lovesticker",
                  "rabbit",
                  "pentol",
                  "doge",
                  "gura",
                  "paimon",
                  "patrik",
                  "patrikgif",
                  "Spongebob",*/
                  "attp",
                  "sticker",
                  "stickergif",
                  "take",
                  "stickermeme",
                  "shinobu",
                  "shinobu2"
]
global.wallpapermenu = [
                  "wallpaper",
                  "animewallpaper",
                  "animewall2"
]
global.logomakermenu = [
                  "wolf  *-txt1 | txt2-*",
                  "pornhub  *-txt1 | txt2-*",
                  "8bit  *-txt1 | txt2-*",
                  "retro  *-txt1 | txt2-*",
                  "harrypot  *-txt1 | txt2-*",
                  "graffiti  *-txt1 | txt2-*",
                  "pornhub2  *-txt1 | txt2-*",
                  "3Dspace  *-txt1 | txt2-*",
                  "lion  *-txt1 | txt2-*",
                  "bear  *-txt1 | txt2-*",
                  "horror  *-txt1 | txt2-*",
                  "whitebear  *-txt1 | txt2-*",
                  "backpink  *-txt1 | txt2-*",
                  "neon  *-txt1 | txt2-*",
                  "matrix2  *-txt1 | txt2-*",
                  "sky  *-txt1 | txt2-*",
                  "magma  *-txt1 | txt2-*",
                  "sand  *-txt1 | txt2-*",
                  "metalic  *-txt1 | txt2-*",
                  "steel  *-txt1 | txt2-*",
                  "luxury  *-txt1 | txt2-*",
                  "glue2  *-txt1 | txt2-*",
                  "fabric  *-txt1 | txt2-*",
                  "lava  *-txt1 | txt2-*",
                  "toxic  *-txt1 | txt2-*",
                  "ancient  *-txt1 | txt2-*",
                  "christmas  *-txt1 | txt2-*",
                  "sci_fi  *-txt1 | txt2-*",
                  "rainbow  *-txt1 | txt2-*",
                  "classic  *-txt1 | txt2-*",
                  "watercolor2  *-txt1 | txt2-*",
                  "halloween2  *-txt1 | txt2-*",
                  "halloweenfire  *-txt1 | txt2-*",
                  "writing  *-txt1 | txt2-*",
                  "Marvel  *-txt1 | txt2-*",
                  "skeleton2  *-txt1 | txt2-*",
                  "sketch  *-txt1 | txt2-*",
                  "wonderfull  *-txt1 | txt2-*",
                  "cool  *-txt1 | txt2-*",
                  "collwall  *-txt1 | txt2-*",
                  "multicolour2  *-txt1 | txt2-*",
                  "batman  *-txt1 | txt2-*",
                  "juice  *-txt1 | txt2-*"
]
global.textpromenu = [
                  "neonlight2 *-text-*",
                  "thewall *-text-*",
                  "natural *-text-*",
                  "carbon *-text-*",
                  "pencil *-text-*",
                  "thunder *-text-*",
                  "blackpinkneon *-text-*",
                  "blackpink2 *-text-*",
                  "3dneon *-text-*",
                  "greenneon *-text-*",
                  "bokeh *-text-*",
                  "3Dbox *-text-*",
                  "waterdrope *-text-*",
                  "papercut *-text-*",
                  "transformer *-text-*",
                  "neondevil *-text-*",
                  "3Davengers *-text-*",
                  "holographic *-text-*",
                  "joker *-text-*",
                  "drapwater *-text-*",
                  "dropewater2 *-text-*",
                  "summertime *-text-*",
                  "candy *-text-*",
                  "christmas *-text-*",
                  "3Dchristmas *-text-*",
                  "sparklechristmas *-text-*",
                  "deepsea *-text-*",
                  "scifi *-text-*",
                  "rainbow2 *-text-*",
                  "waterpipe *-text-*",
                  "spooky *-text-*",
                  "circuit *-text-*",
                  "discovery *-text-*",
                  "metalic *-text-*",
                  "fiction *-text-*",
                  "demon *-text-*",
                  "berry *-text-*",
                  "3Dstone2 *-text-*",
                  "neonlight *-text-*",
                  "glitch *-text-*",
                  "harrypotter *-text-*",
                  "brokenglass *-text-*",
                  "watercolor *-text-*",
                  "multicolor *-text-*",
                  "underwater *-text-*",
                  "graffitibike *-text-*",
                  "snow *-text-*",
                  "cloud *-text-*",
                  "honey *-text-*",
                  "ice *-text-*",
                  "fruitjuice *-text-*",
                  "biscuit *-text-*",
                  "wood *-text-*",
                  "choclate *-text-*",
                  "strawberry *-text-*",
                  "matrix *-text-*",
                  "blood-text *-text-*",
                  "dropewater *-text-*",
                  "toxic *-text-*",
                  "lava *-text-*",
                  "rock *-text-*",
                  "bloodglas *-text-*",
                  "halloween *-text-*",
                  "darkgold *-text-*",
                  "wicker *-text-*",
                  "firework *-text-*",
                  "skeleton *-text-*",
                  "glue *-text-*",
                  "1917 *-text-*",
                  "leaves *-text-*",
                  "demon *-text-*"
]
global.randomimagemenu = [
                  "shinobu2",
                  "megumin2",
                  "anime2",
                  "neko2",
                  "random-girl",
                  "hijaber-girl",
                  "china-girl",
                  "indonesia-girl",
                  "korea-girl",
                  "japan-girl",
                  "malaysia-girl",
                  "thailand-girl",
                  "vietnam-girl"
]
global.animereactionmenu = [
                  "Animeawoo",
                  "Animebite",
                  "Animeblush",
                  "Animebonk",
                  "Animebully",
                  "Animecry",
                  "Animecringe",
                  "Animedance",
                  "Animeglomp",
                  "Animehappy",
                  "Animehandhold",
                  "Animehighfive",
                  "Animehug",
                  "Animekiss",
                  "Animekiss",
                  "Animemegumin",
                  "Animeneko",
                  "Animenom",
                  "Animepat",
                  "Animepoke",
                  "Animeslap",
                  "Animesmile",
                  "Animesmug",
                  "Animespank",
                  "Animewave",
                  "Animewink",
                  "Animewallpaper",
                  "Animeyeet"
]
global.audiomenu = [
               //   "tempo *-audio-*",
                //  "volume *-audio-*",
                  "bass *-audio-*",
                  "blow *-audio-*",
                  "deep *-audio-*",
                  "earrape *-audio-*",
                  "fast *-audio-*",
                  "fat *-audio-*",
                  "nightcore *-audio-*",
                  "reverse *-audio-*",
                  "robot *-audio-*",
                  "slow *-audio-*",
                  "smooth *-audio-*",
                  "squirrel *-audio-*"
]
global.gamemenu = [
                  "leaderboard",
                  "fish",
                  "blood",
                  "mine",
                  "heal",
                  "stab",
                  "hunt",
                  "ttc",
                  "delttc",
         //        "guess *-options-*",
                  "truth",
                  "dare",
                 "leveling",
                  "inventory",
                  "sell",
                  "buy"
]
global.coremenu = [
                  "afk",
           //       "dnd",
                  "co-owner",
                  "react",
                  "rate",
                  "qr",
                  "script",
                  "tutorial",
                  "join",
                  "setexif",
      //            "setname",
                  "block",
                  "unblock",
                  "setbotpp",
                  "restart",
           //       "bcgroup",
          /*        "bctext *-text-*",
                  "bcimage *-pic-*",
                  "bcvideo *-video-*",
               "bcaudio *-audio-*",*/
                  "ebinary",
                  "dbinary",
                  "listgc",
                  "listpc",
               //   "readmore",
           //       "toviewonce",
              //    "tinyurl",
                  "repeat",
                  "modes",
                  "prefix",
    /*              "single-prefix",
                  "multi-prefix",
                  "all-prefix",
                  "no-prefix",
                  "only-admins",*/
                  "settings",
         //         "self",
        //          "public",
      //            "only-admins",
        //          "group-safety",
         /*         "setstatus",
                  "update",*/
                  "ping",
                  "speed",
                  "developer",
                  "owner",
                  "request",
                  "bug",
                  "report",
                  "menu",
                  "info",
                  "tqtt",
                  "support",
                  "weather",
                  "ratebot"
]
global.funmenu = [
                  "awesomecheck *-tag-*",
                  "chutiyacheck *-tag-*",
                  "murderercheck *-tag-*",
                  "greatcheck *-tag-*",
                  "gaycheck *-tag-*",
                  "cutecheck *-tag-*",
                  "lesbiancheck *-tag-*",
                  "hornycheck *-tag-*",
                  "prettycheck *-tag-*",
                  "lovelycheck *-tag-*",
                  "uglycheck *-tag-*",
                  "beautifulcheck *-tag-*",
                  "handsomecheck *-tag-*"
          //        "gamemenu"
]
global.toolmenu = [
                  "ai",
                  "aiimage",
                  "fliptext",
           //       "toletter",
           //       "translate",
                  "emojimix",
                  "fancy"
]/*
global.anonymousmenu = [
                  "start",
                  "stop",
                  "leave",
                  "next" 
]*/
global.nsfwmenu = [
                  "pussy",
                  "SpreadPussy",
                  "Genshin",
                  "Squirt",
                  "Swimsuit",
                  "SchoolSwimsuit",
                  "HoloLive",
                  "Ass",
                  "Underwear",
                  "Nipples",
                  "Uncensored",
                  "Sex",
                  "Sex2",
                  "Sex3",
                  "Blonde",
                  "TwinTails",
                  "Breasts",
                  "ThighHighs",
                  "Skirt",
                  "Gamecg",
                  "AnimalEars",
                  "Foxgirl",
                  "Dress",
                  "SchoolUniform",
                  "TwoGirls",
                  "Gloves",
                  "Vocaloid",
                  "Touhou",
                  "Weapon",
                  "WithFlowers",
                  "PinkHair",
                  "CloudView",
                  "White",
                  "Animal",
                  "Tail",
                  "Nude",
                  "PonyTail",
                  "Bed",
                  "WhiteHair",
                  "Ribbons",
                  "JapaneaseCloths",
                  "HatsuneMiku",
                  "Bikini",
                  "Barefoot",
                  "NoBra",
                  "Food",
                  "Wings",
                  "PantyHouse",
                  "OpenShirt",
                  "HeadBand",
                  "Penis",
                  "Close",
                  "Wet",
                  "CatGirl",
                  "WolfGirl",
                  "Loli2",
                  "SpreadLegs",
                  "Bra",
                  "FateSeries",
                  "Tree",
                  "ElbowGloves",
                  "GreenHair",
                  "Horns",
                  "WithPetals",
                  "Drunk",
                  "Cum",
                  "HeadDress",
                  "Tie",
                  "Shorts",
                  "Maid",
                  "HeadPhones",
                  "AnusView",
                  "Idol",
                  "Gun",
                  "Stockings",
                  "Tears",
                  "BreastHold",
                  "NeckPlace",
                  "SeeThrought",
                  "BunnyEars",
                  "BunnyGirl",
                  "Topless",
                  "Beach",
                  "ErectNipples",
                  "Yuri",
                  "Vampire",
                  "Shirt",
                  "PantyPull",
                  "TornCloths",
                  "BondAge",
                  "Demon",
                  "Bell",
                  "ShirtLift",
                  "Tattoo",
                  "Chain",
                  "FlatChest",
                  "Fingering",
                  "HentaiVideo",
                  "Trap",
                  "hNeko",
                  "nWaifu"
]
global.dare_msg = [
                  "eat 2 tablespoons of rice without any side dishes, if it's dragging you can drink",
                  "spill people who make you pause",
                  "call crush/pickle now and send ss",
                  "drop only emote every time you type on gc/pc for 1 day.",
                  "say Welcome to Who Wants To Be a Millionaire! to all the groups you have",
                  "call ex saying miss",
                  "sing the chorus of the last song you played",
                  "vn your ex/crush/girlfriend, says hi (name), wants to call, just a moment. I miss🥺👉🏼👈🏼",
	              "Bang on the table (which is at home) until you get scolded for being noisy",
                  "Tell random people _I was just told I was your twin first, we separated, then I had plastic surgery. And this is the most ciyusss_ thing",
                  "mention ex's name",
                  "make 1 rhyme for the members!",
                  "send ur whatsapp chat list",
                  "chat random people with gheto language then ss here",
                  "tell your own version of embarrassing things",
                  "tag the person you hate",
                  "Pretending to be possessed, for example: possessed by dog, possessed by grasshoppers, possessed by refrigerator, etc.",
                  "change name to *I AM DONKEY* for 24 hours",
                  "shout *ma chuda ma chuda ma chuda* in front of your house",
                  "snap/post boyfriend photo/crush",
                  "tell me your boyfriend type!",
                  "say *i hv crush on you, do you want to be my girlfriend?* to the opposite sex, the last time you chatted (submit on wa/tele), wait for him to reply, if you have, drop here",
                  "record ur voice that read *titar ke age do titar, titar ke piche do titar*",
                  "prank chat ex and say *i love u, please come back.* without saying dare!",
                  "chat to contact wa in the order according to your battery %, then tell him *i am lucky to hv you!*",
                  "change the name to *I am a child of randi* for 5 hours",
                  "type in bengali 24 hours",
                  "Use selmon bhoi photo for 3 days",
                  "drop a song quote then tag a suitable member for that quote",
                  "send voice note saying can i call u baby?",
                  "ss recent call whatsapp",
                  "Say *YOU ARE SO BEAUTIFUL DON'T LIE* to guys!",
                  "pop to a group member, and say fuck you",
                  "Act like a chicken in front of ur parents",
                  "Pick up a random book and read one page out loud in vn n send it here",
                  "Open your front door and howl like a wolf for 10 seconds",
                  "Take an embarrassing selfie and paste it on your profile picture",
                  "Let the group choose a word and a well known song. You have to sing that song and send it in voice note",
                  "Walk on your elbows and knees for as long as you can",
                  "sing national anthem in voice note",
                  "Breakdance for 30 seconds in the sitting room😂",
                  "Tell the saddest story you know",
                  "make a twerk dance video and put it on status for 5mins",
                  "Eat a raw piece of garlic",
                  "Show the last five people you texted and what the messages said",
                  "put your full name on status for 5hrs",
                  "make a short dance video without any filter just with a music and put it on ur status for 5hrs",
                  "call ur bestie, bitch",
                  "put your photo without filter on ur status for 10mins",
                  "say i love oli london in voice note🤣🤣",
                  "Send a message to your ex and say I still like you",
                  "call Crush/girlfriend/bestie now and screenshot here",
                  "pop to one of the group member personal chat and Say you ugly bustard",
                  "say YOU ARE BEAUTIFUL/HANDSOME to one of person who is in top of ur pinlist or the first person on ur chatlist",
                  "send voice notes and say, can i call u baby, if u r boy tag girl/if girl tag boy",
                  "write i love you (random grup member name, who is online) in personal chat, (if u r boy write girl name/if girl write boy name) take a snap of the pic and send it here",
                  "use any bollywood actor photo as ur pfp for 3 days",
                  "put your crush photo on status with caption, this is my crush",
                  "change name to I AM GAY for 5 hours",
                  "chat to any contact in whatsapp and say i will be ur bf/gf for 5hours",
                  "send voice note says i hv crush on you, want to be my girlfriend/boyfriend or not? to any random person from the grup(if u girl choose boy, if boy choose girl",
                  "slap ur butt hardly send the sound of slap through voice note😂",
                  "state ur gf/bf type and send the photo here with caption, ugliest girl/boy in the world",
                  "shout bravooooooooo and send here through voice note",
                  "snap your face then send it here",
                  "Send your photo with a caption, i am lesbian",
                  "shout using harsh words and send it here through vn",
                  "shout you bastard in front of your mom/papa",
                  "change the name to i am idiot for 24 hours",
                  "slap urself firmly and send the sound of slap through voice note😂",
                  "say i love the bot owner Pika through voice note",
                  "send your gf/bf pic here",
                  "make any tiktok dance challenge video and put it on status, u can delete it after 5hrs",
                  "breakup with your best friend for 5hrs without telling him/her that its a dare",
                  "tell one of your frnd that u love him/her and wanna marry him/her, without telling him/her that its a dare",
                  "say i love depak kalal through voice note",
                  "write i am feeling horny and put it on status, u can delete it only after 5hrs",
                  "write i am lesbian and put it on status, u can delete only after 5hrs",
                  "kiss your mommy or papa and say i love you😌",
                  "put your father name on status for 5hrs",
                  "send abusive words in any grup, excepting this grup, and send screenshot proof here"
]
global.truth_msg = [
                  "Have you ever liked anyone? How long?",
                  "If you can or if you want, which gc/outside gc would you make friends with? (maybe different/same type)",
                  "apa ketakutan terbesar kamu?",
                  "Have you ever liked someone and felt that person likes you too?",
                  "What is the name of your friend's ex-girlfriend that you used to secretly like?",
                  "Have you ever stolen money from your father or mom? The reason?",
                  "What makes you happy when you're sad?",
                  "Ever had a one sided love? if so who? how does it feel bro?", 
                  "been someone's mistress?",
                  "the most feared thing",
                  "Who is the most influential person in your life?",
                  "what proud thing did you get this year", 
                  "Who is the person who can make you awesome", 
                  "Who is the person who has ever made you very happy?", 
                  "Who is closest to your ideal type of partner here", 
                  "Who do you like to play with??", 
                  "Have you ever rejected people? the reason why?",
                  "Mention an incident that made you hurt that you still remember", 
                  "What achievements have you got this year??",
                  "What's your worst habit at school??",
                  "What song do you sing most in the shower",
                  "Have you ever had a near-death experience",
                  "When was the last time you were really angry. Why?",
                  "Who is the last person who called you",
                  "Do you have any hidden talents, What are they",
                  "What word do you hate the most?",
                  "What is the last github video you watched?",
                  "What is the last thing you Googled",
                  "Who in this group would you want to swap lives with for a week",
                  "What is the scariest thing thats ever happened to you",
                  "Have you ever farted and blamed it on someone else",
                  "When is the last time you made someone else cry",
                  "Have you ever ghosted a friend",
                  "Have you ever seen a dead body",
                  "Which of your family members annoys you the most and why",
                  "If you had to delete one app from your phone, which one would it be",
                  "What app do you waste the most time on",
                  "Have you ever faked sick to get home from school",
                  "What is the most embarrassing item in your room",
                  "What five items would you bring if you got stuck on a desert island",
                  "Have you ever laughed so hard you peed your pants",
                  "Do you smell your own farts",
                  "have u ever peed on the bed while sleeping ðŸ¤£ðŸ¤£",
                  "What is the biggest mistake you have ever made",
                  "Have you ever cheated in an exam",
                  "What is the worst thing you have ever done",
                  "When was the last time you cried",
                  "whom do you love the most among ur parents", 
                  "do u sometimes put ur finger in ur nosetrilðŸ¤£", 
                  "who was ur crush during the school days",
                  "tell honestly, do u like any boy in this grup",
                  "have you ever liked anyone? how long?",
                  "do you have gf/bf','what is your biggest fear?",
                  "have you ever liked someone and felt that person likes you too?",
                  "What is the name of your ex boyfriend of your friend that you once liked quietly?",
                  "ever did you steal your mothers money or your fathers money",
                  "what makes you happy when you are sad",
                  "do you like someone who is in this grup? if you then who?",
                  "have you ever been cheated on by people?",
                  "who is the most important person in your life",
                  "what proud things did you get this year",
                  "who is the person who can make you happy when u r sad",
                  "who is the person who ever made you feel uncomfortable",
                  "have you ever lied to your parents",
                  "do you still like ur ex",
                  "who do you like to play together with?",
                  "have you ever stolen big thing in ur life? the reason why?",
                  "Mention the incident that makes you hurt that you still remember",
                  "what achievements have you got this year?",
                  "what was your worst habit at school?",
                  "do you love the bot creator, Pika?ðŸ¦„",
                  "have you ever thought of taking revenge from ur teacher?",
                  "do you like current prime minister of ur country",
                  "you non veg or veg",
                  "if you could be invisible, what is the first thing you would do",
                  "what is a secret you kept from your parents",
                  "Who is your secret crush",
                  "whois the last person you creeped on social media",
                  "If a genie granted you three wishes, what would you ask for",
                  "What is your biggest regret",
                  "What animal do you think you most look like",
                  "How many selfies do you take a day",
                  "What was your favorite childhood show",
                  "if you could be a fictional character for a day, who would you choose",
                  "whom do you text the most",
                  "What is the biggest lie you ever told your parents",
                  "Who is your celebrity crush",
                  "Whats the strangest dream you have ever had",
                  "do you play pubg, if you then send ur id number"
]
let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update'${__filename}'`))
	delete require.cache[file]
	require(file)
})
