exports.cmdName = () => {
  return {
    name: ['dalle'],
    category: "ai",
    alias: ['aiimg','aipic'],
    desc: "This command generates images from text prompts."
  };
}

exports.getCommand = async (text, prefix, anyaV2, command, pika) => {
  require('../../config');
  await pika.react("🤖");
  const { get } = require('axios');
  if (!text) return pika.reply(`*Example:* *${prefix + command}* Beautiful anime girl on a bike.`);
  try {
    pika.reply(message.wait);
    let min = 0;
    let max = 3; // don't put more than 4
    const response = await get(`https://vihangayt.me/tools/aiimg?q=${text}`);
    if (response.data.data.aiImageData.length === 0) return pika.reply("No results found");
    for (let image of response.data.data.aiImageData) {
    if (min++ === max) return;
    anyaV2.sendMessage(pika.chat, {
        image: { url: image.imageHighResolution.url },
        caption: `*🌟 Query:* ${text}\n_Generated by ${global.botname}_`
        }, { quoted:pika });
     }
  } catch (error) {
    console.log(error);
    return pika.reply(message.error);
  }
}
