const { anya } = require('../lib');

anya({
  name: [
    "pussy",
    "spreadpussy",
    "genshin",
    "squirt",
    "swimsuit",
    "schoolswimsuit",
    "holoLive",
    "ass",
    "underwear",
    "nipples",
    "uncensored",
    "sex",
    "sex2",
    "sex3",
    "blonde",
    "twintails",
    "breasts",
    "thighhighs",
    "skirt",
    "gamecg",
    "animalears",
    "foxgirl",
    "dress",
    "schooluniform",
    "twogirls",
    "gloves",
    "vocaloid",
    "touhou",
    "weapon",
    "withflowers",
    "pinkhair",
    "cloudview",
    "white",
    "animal",
    "tail",
    "nude",
    "ponyTail",
    "bed",
    "whitehair",
    "ribbons",
    "japaneasecloths",
    "hatsunemiku",
    "bikini",
    "barefoot",
    "nobra",
    "food",
    "wings",
    "pantyhouse",
    "openshirt",
    "headband",
    "penis",
    "close",
    "wet",
    "catgirl",
    "wolfgirl",
    "loli2",
    "spreadlegs",
    "bra",
    "fateseries",
    "tree",
    "elbowgloves",
    "greenhair",
    "horns",
    "withpetals",
    "drunk",
    "cum",
    "headdress",
    "tie",
    "shorts",
    "maid",
    "headphones",
    "anusview",
    "idol",
    "gun",
    "stockings",
    "tears",
    "breasthold",
    "neckplace",
    "seethrought",
    "bunnyears",
    "bunnygirl",
    "topless",
    "beach",
    "erectnipples",
    "yuri",
    "vampire",
    "shirt",
    "pantypull",
    "torncloths",
    "bondage",
    "demon",
    "bell",
    "shirtlift",
    "tattoo",
    "chain",
    "flatchest",
    "fingering"
  ],
  alias: [],
  react: "🤤",
  category: "nsfw",
  desc: "Not safe for work nudity, seducive commands",
  filename: "/workspaces/Anya_v2-MD/test.js"
}, 
async (anyaV2, pika, group, command) => {
  const Config = require('../../config');
  if (!pika.isGroup) return pika.reply(Config.message.group);
  if (!group.nsfw) return pika.reply(Config.message.nsfw);
  const axios = require('axios');
  const { myfunc } = require('../lib');
  axios.get(`https://fantox-apis.vercel.app/${command}`)
  .then(async (res, err) => {
    if (err) return pika.reply(Config.message.error + '\n\n' + err);
    anyaV2.sendMessage(pika.chat, {
      image: await myfunc.getBuffer(res.data.url),
      caption: `_Reply 1 for more '${command}'  🥵_\n_ID: QA06_`,
      contextInfo: {
        externalAdReply: {
          title: 'NSFW ' + Config.botname,
          body: `Owner: ${Config.ownername}`,
          thumbnail: Config.image_2,
        //  sourceUrl: 'https://github.com/PikaBotz/Anya_v2-MD',
        //  mediaUrl: 'https://github.com/PikaBotz/Anya_v2-MD'
        }
      }
    }, { quoted: pika });
  });
});
